# Fine-Tuning Experiments

Этот ноутбук нужен для демонстрации этапа экспериментов:
- проверка структуры датасета;
- запуск обучения двух моделей;
- подбор гиперпараметров;
- экспорт лучшей модели в ONNX;
- просмотр результатов.

In [1]:
from pathlib import Path
import json
import pandas as pd

PROJECT_ROOT = Path.cwd().resolve().parents[0] if Path.cwd().name == "experiments" else Path.cwd()
PROJECT_ROOT

PosixPath('/Users/ansat/Desktop/Info/Учеба/6 семестр/Нейросетевые технологии/lab3')

In [2]:
DATA_ROOT = PROJECT_ROOT / "data" / "raw" / "my_dataset"
for split in ["train", "val", "test"]:
    split_path = DATA_ROOT / split
    print(f"\n{split_path}:")
    for cls_dir in sorted(split_path.iterdir()):
        if cls_dir.is_dir():
            print(cls_dir.name, len(list(cls_dir.glob("*"))))

/Users/ansat/Desktop/Info/Учеба/6 семестр/Нейросетевые технологии/lab3/data/raw/my_dataset/train:
headphones 6
keyboard 6
mug 6

/Users/ansat/Desktop/Info/Учеба/6 семестр/Нейросетевые технологии/lab3/data/raw/my_dataset/val:
headphones 6
keyboard 6
mug 6

/Users/ansat/Desktop/Info/Учеба/6 семестр/Нейросетевые технологии/lab3/data/raw/my_dataset/test:
headphones 36
keyboard 36
mug 36

## Обучение двух моделей

In [9]:
import subprocess
import sys

cmd = [
    sys.executable,
    str(PROJECT_ROOT / "experiments" / "train.py"),
    "--data-dir", "data/raw/my_dataset",
    "--epochs", "8",
    "--freeze-epochs", "3",
]
subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 1/8 | train_loss=1.1286 train_acc=0.2778 | val_loss=1.0853 val_acc=0.3889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 2/8 | train_loss=1.0874 train_acc=0.4444 | val_loss=1.0507 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 3/8 | train_loss=1.0230 train_acc=0.6667 | val_loss=1.0188 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 4/8 | train_loss=1.0227 train_acc=0.7222 | val_loss=1.0218 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 5/8 | train_loss=1.0069 train_acc=0.6111 | val_loss=1.0276 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 6/8 | train_loss=1.0170 train_acc=0.6667 | val_loss=1.0283 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 7/8 | train_loss=0.9368 train_acc=0.9444 | val_loss=1.0126 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 8/8 | train_loss=0.9168 train_acc=0.8889 | val_loss=1.0154 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 1/8 | train_loss=1.1280 train_acc=0.4444 | val_loss=0.9582 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 2/8 | train_loss=0.7396 train_acc=0.9444 | val_loss=0.7219 val_acc=0.9444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 3/8 | train_loss=0.4179 train_acc=1.0000 | val_loss=0.5619 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 4/8 | train_loss=0.2286 train_acc=1.0000 | val_loss=0.5208 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 5/8 | train_loss=0.2105 train_acc=0.9444 | val_loss=0.4829 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 6/8 | train_loss=0.1394 train_acc=1.0000 | val_loss=0.4407 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 7/8 | train_loss=0.2030 train_acc=0.8889 | val_loss=0.4130 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 8/8 | train_loss=0.1952 train_acc=0.9444 | val_loss=0.4008 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

        model_name  test_accuracy  best_val_accuracy  training_seconds
1  efficientnet_b0       1.000000           1.000000            239.97
0         resnet18       0.731481           0.722222            217.08

CompletedProcess(args=['/Users/ansat/.pyenv/versions/3.12.0/bin/python', '/Users/ansat/Desktop/Info/Учеба/6 семестр/Нейросетевые технологии/lab3/experiments/train.py', '--data-dir', 'data/raw/my_dataset', '--epochs', '8', '--freeze-epochs', '3'], returncode=0)

## Просмотр таблицы результатов

In [10]:
results_path = PROJECT_ROOT / "models" / "results.csv"
pd.read_csv(results_path)

,model_name,test_loss,test_accuracy,best_val_accuracy,training_seconds,checkpoint_path,class_names,history
0,efficientnet_b0,0.524648,1.000000,1.000000,239.97,models/efficientnet_b0_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.1280032926135592, 0.73960428..."
1,resnet18,1.007894,0.731481,0.722222,217.08,models/resnet18_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.1285929017596774, 1.08738938..."

## Подбор гиперпараметров

In [11]:
cmd = [
    sys.executable,
    str(PROJECT_ROOT / "experiments" / "train.py"),
    "--data-dir", "data/raw/my_dataset",
    "--run-sweep",
    "--epochs", "6",
    "--freeze-epochs", "2",
]
subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

Запуск sweep #1: model=resnet18, batch_size=8, lr_head=0.001

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 1/6 | train_loss=1.0974 train_acc=0.3333 | val_loss=1.0676 val_acc=0.3889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 2/6 | train_loss=1.0724 train_acc=0.3333 | val_loss=1.0293 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 3/6 | train_loss=1.0102 train_acc=0.7222 | val_loss=1.0190 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 4/6 | train_loss=0.9807 train_acc=0.6667 | val_loss=1.0234 val_acc=0.6111

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 5/6 | train_loss=0.9585 train_acc=0.7222 | val_loss=1.0278 val_acc=0.6111

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 6/6 | train_loss=0.9896 train_acc=0.6667 | val_loss=1.0117 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #2: model=efficientnet_b0, batch_size=8, lr_head=0.001

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 1/6 | train_loss=1.0636 train_acc=0.3889 | val_loss=0.8366 val_acc=0.8333

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 2/6 | train_loss=0.6555 train_acc=0.9444 | val_loss=0.5872 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 3/6 | train_loss=0.4359 train_acc=0.9444 | val_loss=0.5222 val_acc=0.9444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 4/6 | train_loss=0.3410 train_acc=1.0000 | val_loss=0.4604 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 5/6 | train_loss=0.1933 train_acc=1.0000 | val_loss=0.4276 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 6/6 | train_loss=0.2624 train_acc=1.0000 | val_loss=0.3962 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #3: model=resnet18, batch_size=8, lr_head=0.0003

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 1/6 | train_loss=1.0754 train_acc=0.3889 | val_loss=1.0917 val_acc=0.2778

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 2/6 | train_loss=1.0601 train_acc=0.5000 | val_loss=1.0834 val_acc=0.3889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 3/6 | train_loss=1.0694 train_acc=0.3333 | val_loss=1.0691 val_acc=0.3333

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 4/6 | train_loss=1.0377 train_acc=0.6111 | val_loss=1.0618 val_acc=0.3333

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 5/6 | train_loss=0.9753 train_acc=0.7222 | val_loss=1.0432 val_acc=0.3889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 6/6 | train_loss=0.9886 train_acc=0.7222 | val_loss=1.0351 val_acc=0.5000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #4: model=efficientnet_b0, batch_size=8, lr_head=0.0003

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 1/6 | train_loss=1.0599 train_acc=0.5000 | val_loss=1.0782 val_acc=0.4444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 2/6 | train_loss=0.9782 train_acc=0.6111 | val_loss=0.9875 val_acc=0.6111

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 3/6 | train_loss=0.8278 train_acc=0.8889 | val_loss=0.9144 val_acc=0.8333

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 4/6 | train_loss=0.7075 train_acc=0.9444 | val_loss=0.8232 val_acc=0.8889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 5/6 | train_loss=0.5248 train_acc=1.0000 | val_loss=0.7433 val_acc=0.9444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 6/6 | train_loss=0.5991 train_acc=0.9444 | val_loss=0.6905 val_acc=0.9444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #5: model=resnet18, batch_size=16, lr_head=0.001

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 1/6 | train_loss=1.1078 train_acc=0.3889 | val_loss=1.1000 val_acc=0.2222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 2/6 | train_loss=1.0402 train_acc=0.6111 | val_loss=1.0625 val_acc=0.3889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 3/6 | train_loss=1.0451 train_acc=0.6111 | val_loss=1.0357 val_acc=0.5000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 4/6 | train_loss=0.9883 train_acc=0.6111 | val_loss=1.0245 val_acc=0.5000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 5/6 | train_loss=0.9649 train_acc=0.7778 | val_loss=1.0073 val_acc=0.5556

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 6/6 | train_loss=0.9657 train_acc=0.7778 | val_loss=0.9990 val_acc=0.7778

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #6: model=efficientnet_b0, batch_size=16, lr_head=0.001

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 1/6 | train_loss=1.0696 train_acc=0.3889 | val_loss=0.8659 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 2/6 | train_loss=0.7142 train_acc=1.0000 | val_loss=0.6622 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 3/6 | train_loss=0.4619 train_acc=1.0000 | val_loss=0.6140 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 4/6 | train_loss=0.3773 train_acc=0.9444 | val_loss=0.5523 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 5/6 | train_loss=0.2798 train_acc=1.0000 | val_loss=0.5037 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 6/6 | train_loss=0.2220 train_acc=1.0000 | val_loss=0.4782 val_acc=1.0000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #7: model=resnet18, batch_size=16, lr_head=0.0003

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 1/6 | train_loss=1.0966 train_acc=0.2778 | val_loss=1.0476 val_acc=0.4444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 2/6 | train_loss=1.0616 train_acc=0.5000 | val_loss=1.0362 val_acc=0.4444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 3/6 | train_loss=1.0268 train_acc=0.5000 | val_loss=1.0227 val_acc=0.5556

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 4/6 | train_loss=1.0181 train_acc=0.5556 | val_loss=1.0196 val_acc=0.5000

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 5/6 | train_loss=1.0194 train_acc=0.5556 | val_loss=1.0103 val_acc=0.5556

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 6/6 | train_loss=1.0027 train_acc=0.4444 | val_loss=1.0061 val_acc=0.5556

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

Запуск sweep #8: model=efficientnet_b0, batch_size=16, lr_head=0.0003

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 1/6 | train_loss=1.0724 train_acc=0.4444 | val_loss=0.9727 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 2/6 | train_loss=0.9853 train_acc=0.5556 | val_loss=0.8955 val_acc=0.8333

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 3/6 | train_loss=0.8594 train_acc=0.8333 | val_loss=0.8426 val_acc=0.8889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 4/6 | train_loss=0.7398 train_acc=1.0000 | val_loss=0.7864 val_acc=0.8889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 5/6 | train_loss=0.5829 train_acc=0.9444 | val_loss=0.7382 val_acc=0.9444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[efficientnet_b0] epoch 6/6 | train_loss=0.5110 train_acc=1.0000 | val_loss=0.7023 val_acc=0.9444

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

        model_name  batch_size  lr_head  test_accuracy  best_val_accuracy
1  efficientnet_b0           8   0.0010       0.990741           1.000000
7  efficientnet_b0          16   0.0003       0.981481           0.944444
5  efficientnet_b0          16   0.0010       0.972222           1.000000
3  efficientnet_b0           8   0.0003       0.944444           0.944444
0         resnet18           8   0.0010       0.787037           0.722222
2         resnet18           8   0.0003       0.722222           0.500000
4         resnet18          16   0.0010       0.648148           0.777778
6         resnet18          16   0.0003       0.518519           0.555556

CompletedProcess(args=['/Users/ansat/.pyenv/versions/3.12.0/bin/python', '/Users/ansat/Desktop/Info/Учеба/6 семестр/Нейросетевые технологии/lab3/experiments/train.py', '--data-dir', 'data/raw/my_dataset', '--run-sweep', '--epochs', '6', '--freeze-epochs', '2'], returncode=0)

In [12]:
sweep_path = PROJECT_ROOT / "models" / "sweep_results.csv"
pd.read_csv(sweep_path)

,model_name,test_loss,test_accuracy,best_val_accuracy,training_seconds,checkpoint_path,class_names,history,batch_size,lr_head
0,efficientnet_b0,0.566700,0.990741,1.000000,175.76,models/efficientnet_b0_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.063641866048177, 0.655483232...",8,0.0010
1,efficientnet_b0,0.661118,0.981481,0.944444,191.80,models/efficientnet_b0_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.0724494987063937, 0.98532757...",16,0.0003
2,efficientnet_b0,0.603020,0.972222,1.000000,195.67,models/efficientnet_b0_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.0695748064253066, 0.71423018...",16,0.0010
3,efficientnet_b0,0.681699,0.944444,0.944444,174.99,models/efficientnet_b0_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.0599220328860812, 0.97817925...",8,0.0003
4,resnet18,0.989619,0.787037,0.722222,164.21,models/resnet18_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.0973936716715496, 1.07238944...",8,0.0010
5,resnet18,1.005328,0.722222,0.500000,161.63,models/resnet18_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.0753682321972318, 1.06005170...",8,0.0003
6,resnet18,1.029830,0.648148,0.777778,167.67,models/resnet18_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.107793304655287, 1.040239837...",16,0.0010
7,resnet18,1.055456,0.518519,0.555556,165.96,models/resnet18_best.pth,"['headphones', 'keyboard', 'mug']","{'train_loss': [1.0966096454196506, 1.06159306...",16,0.0003

## Экспорт лучшей модели в ONNX

In [ ]:
cmd = [
    sys.executable,
    str(PROJECT_ROOT / "experiments" / "train.py"),
    "--data-dir", "data/raw/my_dataset",
    "--epochs", "8",
    "--freeze-epochs", "3",
    "--export-onnx",
    "--onnx-file-name", "best_model.onnx",
]
subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 1/8 | train_loss=1.1286 train_acc=0.2778 | val_loss=1.0853 val_acc=0.3889

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 2/8 | train_loss=1.0874 train_acc=0.4444 | val_loss=1.0507 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 3/8 | train_loss=1.0230 train_acc=0.6667 | val_loss=1.0188 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 4/8 | train_loss=1.0227 train_acc=0.7222 | val_loss=1.0218 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 5/8 | train_loss=1.0069 train_acc=0.6111 | val_loss=1.0276 val_acc=0.6667

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

[resnet18] epoch 6/8 | train_loss=1.0170 train_acc=0.6667 | val_loss=1.0283 val_acc=0.7222

/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/ansat/.pyenv/versions/3.12.0/lib/python3.12/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

In [8]:
summary_path = PROJECT_ROOT / "models" / "best_run_summary.json"
json.loads(summary_path.read_text(encoding="utf-8"))

{'best_model_name': 'efficientnet_b0',
 'results': [{'model_name': 'efficientnet_b0',
   'test_loss': 0.5246480151459023,
   'test_accuracy': 1.0,
   'best_val_accuracy': 1.0,
   'training_seconds': 241.82,
   'checkpoint_path': 'models/efficientnet_b0_best.pth',
   'class_names': ['headphones', 'keyboard', 'mug'],
   'history': {'train_loss': [1.1280032926135592,
     0.7396042810546027,
     0.4179072181383769,
     0.22861369450887045,
     0.2104531791475084,
     0.13938656118181017,
     0.20295900768703884,
     0.19521674844953749],
    'train_acc': [0.4444444444444444,
     0.9444444444444444,
     1.0,
     1.0,
     0.9444444444444444,
     1.0,
     0.8888888888888888,
     0.9444444444444444],
    'val_loss': [0.9582045078277588,
     0.7219453652699789,
     0.5619066291385226,
     0.5208160347408719,
     0.48293089866638184,
     0.4406796296437581,
     0.4129920932981703,
     0.40083498424953884],
    'val_acc': [0.6666666666666666,
     0.9444444444444444,
     1.0,
     1.0,
     1.0,
     1.0,
     1.0,
     1.0]}},
  {'model_name': 'resnet18',
   'test_loss': 1.0078938669628568,
   'test_accuracy': 0.7314814814814815,
   'best_val_accuracy': 0.7222222222222222,
   'training_seconds': 217.2,
   'checkpoint_path': 'models/resnet18_best.pth',
   'class_names': ['headphones', 'keyboard', 'mug'],
   'history': {'train_loss': [1.1285929017596774,
     1.087389389673869,
     1.0230423874325223,
     1.0226750903659396,
     1.0068563554022048,
     1.0170421600341797,
     0.936825712521871,
     0.9167578882641263],
    'train_acc': [0.2777777777777778,
     0.4444444444444444,
     0.6666666666666666,
     0.7222222222222222,
     0.6111111111111112,
     0.6666666666666666,
     0.9444444444444444,
     0.8888888888888888],
    'val_loss': [1.0853393607669406,
     1.050701962576972,
     1.0188160207536485,
     1.0218476984235976,
     1.0276139974594116,
     1.028258548842536,
     1.0126447942521837,
     1.0153911378648546],
    'val_acc': [0.3888888888888889,
     0.6666666666666666,
     0.7222222222222222,
     0.7222222222222222,
     0.6666666666666666,
     0.7222222222222222,
     0.7222222222222222,
     0.6666666666666666]}}],
 'config': {'data': {'data_dir': 'data/raw/my_dataset',
   'image_size': 224,
   'mean': [0.485, 0.456, 0.406],
   'std': [0.229, 0.224, 0.225],
   'num_workers': 2},
  'model': {'model_names': ['resnet18', 'efficientnet_b0'],
   'pretrained': True},
  'train': {'seed': 42,
   'batch_size': 16,
   'epochs': 8,
   'freeze_epochs': 3,
   'lr_head': 0.001,
   'lr_backbone': 0.0001,
   'weight_decay': 0.0001,
   'optimizer': 'adamw',
   'scheduler': 'cosine',
   'label_smoothing': 0.0,
   'device': 'auto'},
  'sweep': {'run_sweep': False,
   'batch_sizes': [8, 16],
   'lr_heads': [0.001, 0.0003]},
  'export': {'export_onnx': True,
   'onnx_opset': 17,
   'onnx_file_name': 'best_model.onnx'},
  'paths': {'output_dir': 'models', 'report_dir': 'reports/figures'}}}